export const TableData = {
         tableHead: [
           "Client ID",
           "Date",
           "Meal Category",
           "Meal Name",
           "Min Portion",
           "Max Portion",
           "Portion",
           "Meal Proteins",
           "Meal Calories",
           "Current Total Calories",
           "Current Total Proteins",
           "Target Calories",
           "Target Proteins",
           "Target Fat",
           "Current Total Fat",
           "Current Total Carb",
           "Actions",
         ],
         roundId: "2",
         startDate: "2022-12-29",
         endDate: "2022-12-29",
         tableBody: [
           {
             ClientID: 1,
             Date: "2022-12-29",
             MealCategory: "Chicken",
             MealName: "Chicken Curry",
             mealId: "63b4710e2901459a10a3db7e",
             MinPortion: 150,
             MaxPortion: "160",
             Portion: "110",
             MealProteins: "450",
             MealCalories: "450",
             CurrentTotalCalories: "1658",
             CurrentTotalProteins: "110",
             TargetCalories: "1700",
             TargetProteins: "115",
             minservingCarbs: 39, //min carbs
             minservingfat: 3, //min fat
             minservingprotein: 3,
             TargetFat: "20",
             CurrentTotalFat: "20",
             CurrentTotalCarb: 20,
           },
           {
             ClientID: 2,
             Date: "2022-12-29",
             MealCategory: "Chicken",
             mealId: "",
             MealName: "hicken Curry",
             MinPortion: 150,
             MaxPortion: "160",
             Portion: "110",
             MealProteins: "450",
             MealCalories: "450",
             CurrentTotalCalories: "1658",
             CurrentTotalProteins: "110",
             TargetCalories: "1700",
             TargetProteins: "115",
             minservingCarbs: 39, //min carbs
             minservingfat: 3, //min fat
             minservingprotein: 3,
             TargetFat: "20",
             CurrentTotalFat: "20",
             CurrentTotalCarb: "20",
           },
           {
             ClientID: 3,
             Date: "2022-12-29",
             MealCategory: "Chicken",
             mealId: "",
             MealName: "hicken Curry",
             MinPortion: 50,
             MaxPortion: "160",
             Portion: "110",
             MealProteins: "450",
             MealCalories: "450",
             CurrentTotalCalories: "1658",
             CurrentTotalProteins: "110",
             TargetCalories: "1700",
             TargetProteins: "115",
             minservingCarbs: 39, //min carbs
             minservingfat: 3, //min fat
             minservingprotein: 3,
             TargetFat: "20",
             CurrentTotalFat: "20",
             CurrentTotalCarb: "20",
           },
           {
             ClientID: 4,
             Date: "2022-12-27",
             MealCategory: "Chicken",
             mealId: "",
             MealName: "hicken Curry",
             MinPortion: 50,
             MaxPortion: "160",
             Portion: "110",
             MealProteins: "450",
             MealCalories: "450",
             CurrentTotalCalories: "1658",
             CurrentTotalProteins: "110",
             TargetCalories: "1700",
             TargetProteins: "115",
             minservingCarbs: 39, //min carbs
             minservingfat: 3, //min fat
             minservingprotein: 3,
             TargetFat: "20",
             CurrentTotalFat: "20",
             CurrentTotalCarb: "20",
           },
           {
             ClientID: 5,
             Date: "2022-12-28",
             MealCategory: "Chicken",
             mealId: "",
             MealName: "hicken Curry",
             MinPortion: 50,
             MaxPortion: "160",
             Portion: "110",
             MealProteins: "450",
             MealCalories: "450",
             CurrentTotalCalories: "1658",
             CurrentTotalProteins: "110",
             TargetCalories: "1700",
             TargetProteins: "115",
             minservingCarbs: 39, //min carbs
             minservingfat: 3, //min fat
             minservingprotein: 3,
             TargetFat: "20",
             CurrentTotalFat: "20",
             CurrentTotalCarb: "20",
           },
           {
             ClientID: 6,
             Date: "2022-12-28",
             MealCategory: "Breakfast",
             mealId: "63c173885f3411b1928929e0",
             MealName: "Breakfast Curry",
             MinPortion: 150,
             MaxPortion: "160",
             Portion: "110",
             MealProteins: "450",
             MealCalories: "450",
             CurrentTotalCalories: "1658",
             CurrentTotalProteins: "110",
             TargetCalories: "1700",
             TargetProteins: "115",
             minservingCarbs: 39, //min carbs
             minservingfat: 3, //min fat
             minservingprotein: 3,
             TargetFat: "20",
             CurrentTotalFat: "20",
             CurrentTotalCarb: "20",
           },
         ],
       };
export const apiData = {
  roundId: 20,
  startDate: "2022-12-29T00:00:00.000Z",
  endDate: "2022-12-30T00:00:00.000Z",
  _id: "640327b75d023f8c2ae3cb24",
  mealSettings: [
    {
      categoryName: "Breakfast",
      mealId: "63c173885f3411b1928929e0",
      clients: [
        {
          clientId: 6,
          uncookedPlannedPortion: 1620,
          boxNumber: 3,
          _id: "63d6b579d6fa787b72d42917",
        },
        {
          clientId: 1,
          uncookedPlannedPortion: 225,
          boxNumber: 3,
          _id: "63d6b579d6fa787b72d42926",
        },
      ],
      _id: "63d6b579d6fa787b72d42916",
      plannedIngredients: [],
      actualIngredients: [],
    },
    {
      categoryName: "Chicken",
      mealId: "63b4710e2901459a10a3db7e",
      clients: [
        {
          clientId: 5,
          uncookedPlannedPortion: 50,
          boxNumber: 3,
          _id: "63d6b579d6fa787b72d42919",
        },
        {
          clientId: 5,
          uncookedPlannedPortion: 50,
          boxNumber: 1,
          _id: "63d6b579d6fa787b72d42920",
        },
        {
          clientId: 2,
          uncookedPlannedPortion: 50,
          boxNumber: 1,
          _id: "63d6b579d6fa787b72d42924",
        },
        {
          clientId: 1,
          uncookedPlannedPortion: 50,
          boxNumber: 3,
          _id: "63d6b579d6fa787b72d42927",
        },
        {
          clientId: 1,
          uncookedPlannedPortion: 50,
          boxNumber: 1,
          _id: "63d6b579d6fa787b72d4292a",
        },
      ],
      _id: "63d6b579d6fa787b72d42918",
      plannedIngredients: [],
      actualIngredients: [],
    },
  ],
};
