export const TableData = {
    tableHead: ["Client ID", "Date", "Meal Category", "Meal Name", "Min Portion", "Max Portion", "Portion", "Meal Calories", "Current Total Calories",
        "Current Total Proteins", "Target Calories", "Target Proteins"],
    roundId: "2",
    startDate: "2022-12-29",
    endDate: "2022-12-29",
    tableBody: [
        {
            ClientID: "1",
            Date: "2022-12-29",
            MealCategory: "Chicken",
            MealName: "Chicken Curry",
            MinPortion: "50",
            MaxPortion: "160",
            Portion: "110",
            MealCalories: "450",
            CurrentTotalCalories: "1658",
            CurrentTotalProteins: "110",
            TargetCalories: "1700",
            TargetProteins: "115"
        },
        {
            ClientID: "2",
            Date: "2022-12-29",
            MealCategory: "Chicken",
            MealName: "hicken Curry",
            MinPortion: "50",
            MaxPortion: "160",
            Portion: "110",
            MealCalories: "450",
            CurrentTotalCalories: "1658",
            CurrentTotalProteins: "110",
            TargetCalories: "1700",
            TargetProteins: "115"
        },
        {
            ClientID: "3",
            Date: "2022-12-29",
            MealCategory: "Chicken",
            MealName: "hicken Curry",
            MinPortion: "50",
            MaxPortion: "160",
            Portion: "110",
            MealCalories: "450",
            CurrentTotalCalories: "1658",
            CurrentTotalProteins: "110",
            TargetCalories: "1700",
            TargetProteins: "115"
        },
        {
            ClientID: "4",
            Date: "2022-12-29",
            MealCategory: "Chicken",
            MealName: "hicken Curry",
            MinPortion: "50",
            MaxPortion: "160",
            Portion: "110",
            MealCalories: "450",
            CurrentTotalCalories: "1658",
            CurrentTotalProteins: "110",
            TargetCalories: "1700",
            TargetProteins: "115"
        },
        {
            ClientID: "5",
            Date: "2022-12-29",
            MealCategory: "Chicken",
            MealName: "hicken Curry",
            MinPortion: "50",
            MaxPortion: "160",
            Portion: "110",
            MealCalories: "450",
            CurrentTotalCalories: "1658",
            CurrentTotalProteins: "110",
            TargetCalories: "1700",
            TargetProteins: "115"
        },
        {
            ClientID: "6",
            Date: "2022-12-29",
            MealCategory: "Chicken",
            MealName: "hicken Curry",
            MinPortion: "50",
            MaxPortion: "160",
            Portion: "110",
            MealCalories: "450",
            CurrentTotalCalories: "1658",
            CurrentTotalProteins: "110",
            TargetCalories: "1700",
            TargetProteins: "115"
        },

    ],
};
